# Generated by Django 5.2.3 on 2025-06-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorregistration',
            name='hours_to_stay',
            field=models.IntegerField(help_text='Enter the number of hours you plan to stay', null=True),
        ),
    ]
